server:
  port: 8090

spring:
#  main:
#    web-application-type: none
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://117.72.147.196:15432/ai-rag-knowledge
    type: com.zaxxer.hikari.HikariDataSource
  ai:
    mcp:
      client:
        request-timeout: 360s
        sse:
          connections:
            mcp-server-csdn:
              url: http://127.0.0.1:8101
            mcp-server-weixin:
              url: http://127.0.0.1:8102
#        stdio:
#          servers-configuration: classpath:/config/mcp-servers-config-4.json
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/
      api-key: sk-18ecc9ed836f4661ac299bf0ed97201e
      chat:
        options:
          model: qwen-plus
      embedding-model: text-embedding-v4
      embedding:
        options:
          num-batch: 1536
    ollama:
      base-url: http://f3fea4e35e67457bb199-deepseek-r1-llm-api.gcs-xy1a.jdcloud.com/
      mode:
      embedding-model: nomic-embed-text
      embedding:
        options:
          num-batch: 768

logging:
  level:
    root: info
  config: classpath:logback-spring.xml
